//LOCALHOST
### GET all contact
GET http://localhost:9090/contacts

### GET contact by id
GET http://localhost:9090/contacts/6869a49eb54c7f0459144452

//PRODUCTION
### GET all contact
GET https://cse-341-project1-a51f.onrender.com/contacts

### GET contact by id
GET https://cse-341-project1-a51f.onrender.com/contacts/6869a49eb54c7f0459144452
